### ISSUE TITLE
[NFC]: emv_render calls nfc_render_emv_name, which is declared but never defined

### ISSUE THREAD

**Issue by mishamyte** [DarkFlippers/unleashed-firmware#1084]
## Describe the bug

`applications/main/nfc/helpers/protocol_support/emv/emv_render.c:35` calls `nfc_render_emv_name(...)`, declared at `emv_render.h:14` — and that function **has no definition anywhere in the tree**.

It is not a link error today only because its sole caller, `nfc_render_emv_data` (`emv_render.c:33`), has no callers itself, so `--gc-sections` discards the whole island before the linker has to resolve anything.

## Impact

Latent. The moment anyone wires `nfc_render_emv_data` into a render path, `nfc_emv.fal` gains an unresolved import — and `do_strict_import_checks` returns `false` for `FlipperAppType.PLUGIN` (`scripts/fbt/appmanifest.py:111`), so `APPCHK` only *warns*. The build stays green and the plugin ships as one that silently never loads.

That is exactly the failure mode that kept `nfc_emv.fal` from ever loading on `dev` until PR #1073 fixed it — the same trap, one function away.

## Expected

Either define `nfc_render_emv_name`, or delete the dead island: `nfc_render_emv_data` (`:33`), `nfc_render_emv_pan` (`:38`) and the `nfc_render_emv_name` declaration.

## Related

Worth considering separately whether plugin import checks should be strict rather than warning-only, since a warning in a several-thousand-line build log is not a gate. That is what let the original EMV breakage live for as long as it did.

## Notes

Pre-existing — present at `8bbf9fc09`, not introduced by PR #1073. Found by a review pass on that PR.

**Comment by mishamyte** [comment]
Testing the strict-import-check question from the issue: **it cannot be flipped as-is.**

Forcing `_validate_app_imports` to run against `nfc_mf_classic.fal` reports 36 unresolved symbols, and every one is legitimate — `dict_attack_*`, `detect_reader_*`, `nfc_blink_*`, `nfc_protocol_support_common_*`, `nfc_save_shadow_file`, `nfc_app_run_external`, and four icons. They come from the NFC app's private table (`api/nfc_app_api_table_i.h`) and resolve at runtime through the composite API resolver, but the validator compares only against the firmware SDK. Strict mode would fail all 15 protocol plugins and all 45 parser plugins.

The gap is also wider than the issue assumed: the validator target is attached to plugins but never built, so today no warning is emitted for a `.fal` at all.

A useful version would validate against *firmware SDK ∪ the host app's exported table* — that would have caught this defect and the 47 unresolved imports found during #1073. It is a real change to `fbt` and wants its own issue rather than riding along with the deletion.

Fix in #1085.
